const tradingWisdom = [
  "You never know what kind of setup market will present to you, your objective should be to find an opportunity where risk-reward ratio is best.",
  "A real trader doesn’t pray for a bull run. He profits in any market.",
  "All you need is one pattern to make a living.",
  "Trading doesn’t just reveal your character; it also builds it if you stay in the game long enough.",
  "Every trader has strengths and weaknesses. Some are good holders of winners but may hold their losers a little too long. Others may cut their winners a little short but are quick to take their losses. As long as you stick to your own style, you get the good and bad in your own approach.",
  "The market will humble you if you don’t respect it.",
  "Never risk more than you can afford to lose.",
  "Trading is very competitive and you have to be able to handle getting your butt kicked.",
  "It’s not whether you’re right or wrong that’s important, it’s how much money you make when you’re right and how much you lose when you’re wrong.",
  "If you’re guessing, you’re gambling. If you’re planning, you’re trading.",
  "Do not anticipate and move without market confirmation - being a little late in your trade is your insurance that you are right or wrong.",
  "The stock market is a device for transferring money from the impatient to the patient.",
  "Don’t worry about what the markets are going to do, worry about what you are going to do in response to the markets.",
  "Do not be a hero. Be a smart trader.",
  "An investment in knowledge pays the best interest.",
  "Patterns don't work 100% of the time. But they are still critical because they help you define your risk. If you ignore patterns and focus on hunches, feelings, and hot tips, just forget about achieving consistency.",
  "You have to identify your weaknesses and work to change. Keep a trading diary – write down your reasons for entering and exiting every trade. Look for repetitive patterns of success and failure.",
  "The market is a device for transferring money from the impatient to the patient.",
  "Hope is not a strategy.",
  "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
  "Markets are never wrong – opinions often are.",
  "The moment you accept the risk, you will be at peace with any outcome.",
  "The consistency you seek is in your mind, not in the markets.",
  "The big money is not in the buying and selling, but in the waiting.",
  "Market fluctuations are your friend, not enemy",
  "The goal of a successful trader is to make the best trades. Money is secondary.",
  "Someone is sitting in the shade of a tree today because someone planted a tree a long time ago.",
  "The stock market is filled with individuals who know the price of everything, but the value of nothing.",
  "The single most powerful asset we all have is our mind. If it is trained well, it can create enormous wealth.",
  "When it's raining gold, reach for a bucket, not a thimble.",
  "Never confuse your position with your best interest. Many traders take a position in a stock and form an emotional attachment to it. They'll start losing money, and instead of stopping themselves out, they’ll find brand new reasons to stay in. When in doubt, get out!",
  "Don't test the depth of the river with both your feet while taking the risk",
  "The question should not be how much I will profit on this trade! The true question is; will I be fine if I don't profit from this trade.",
  "Sometimes your best investments are the ones you don’t make.",
  "Never invest in any idea you can’t illustrate with a crayon.",
  "Patterns don’t work 100% of the time. But they are still critical because they help you define your risk. If you ignore patterns and focus on hunches, feelings, and hot tips, just forget about achieving consistency.",
  "Do not be embarrassed by your failures, learn from them and start again.",
  "Your emotions are the fastest way to donate your money to someone smarter.",
  "The market doesn’t owe you anything. Adapt, learn, and improve.",
  "Your strategy doesn’t need to be complicated, just profitable.",
  "Winners execute. Losers hesitate.",
  "A lion doesn’t chase every rabbit. A real trader doesn’t chase every trade.",
];

module.exports = tradingWisdom;
